[build]
  base = "."
  command = "npm ci && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

# Proxy CMS requests to an external Node server
# Replace `https://cms.example.com` with your server's URL
[[redirects]]
  from = "/api/*"
  to = "https://cms.example.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "https://cms.example.com/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/content/*"
  to = "https://cms.example.com/content/:splat"
  status = 200
  force = true

# SPA routing for the main app
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Base security and defaults
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Long cache for hashed assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML shell should not be cached aggressively
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Service worker should not be cached
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
