backend:
  name: github
  ## The GitHub repository slug in the form "owner/repo".
  ## Update this to match your project repository.
  repo: owner/CozyCritters
  branch: main
  ## Use GitHub's implicit OAuth flow for authentication.
  auth_type: implicit
  ## Access is restricted to GitHub collaborators with write permissions.
publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "moods"
    label: "Moods"
    file: "content/moods.json"
    fields:
      - label: "Moods"
        name: "moods"
        widget: "list"
        fields:
          - { label: "Emoji", name: "emoji", widget: "string" }
          - { label: "Mood", name: "mood", widget: "string" }
          - { label: "Color", name: "color", widget: "mood-color" }
  - name: "games"
    label: "Games"
    file: "content/games.json"
    fields:
      - label: "Games"
        name: "games"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Difficulty", name: "difficulty", widget: "game-difficulty" }
  - name: "pages"
    label: "Pages"
    file: "content/pages.json"
    fields:
      - label: "Pages"
        name: "pages"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
